version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket biobeat-test-natali --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
