AWSTemplateFormatVersion: '2010-09-09'
Description: test function 1
Resources:
  testFunction1:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'test_function_1'
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LambdaCode
      Description: 'BioBeat Funtion Test Name Prop'
      Role: arn:aws:iam::656606747806:role/lambda_basic_execution
      MemorySize: 128
      Timeout: 30
