 
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: BioBeat Funtion Test Name Prop
Resources:
  FuntionTestNameProp:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'test_function_name_prop'
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: 'BioBeat Funtion Test Name Prop'
      Role: arn:aws:iam::${AWS::AccountId}:role/lambda_basic_execution
      MemorySize: 128
      Timeout: 30