AWSTemplateFormatVersion: '2010-09-09'
Description: BioBeat Funtion Test Name Prop
Resources:
  FuntionTestNameProp:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'natali'
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaCode
      Description: 'BioBeat Funtion Test Name Prop'
      Role: arn:aws:iam::656606747806:role/lambda_basic_execution
      MemorySize: 128
      Timeout: 30
