AWSTemplateFormatVersion: '2010-09-09'
Description: test function for vpc
Resources:
  testFunction1:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'test_function_for_vpc'
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LambdaCode
      Description: 'BioBeat test function for vpc'
      Role: arn:aws:iam::656606747806:role/service-role/lambda_query_role
      MemorySize: 128
      Timeout: 30
