AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: test function for vpc
Resources:
  testFunctionForVpc:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'test_function_for_vpc'
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LambdaCode
      Description: 'BioBeat test function for vpc'
      Role: arn:aws:iam::656606747806:role/service-role/lambda_query_role
      MemorySize: 128
      Timeout: 30
      VpcConfig:
       SubnetIds:
         - subnet-49dcb220
